INSERT INTO orders (id, type, address, bought_by, currency, delivery_company, img_url, item_full_name, price, telephone) VALUES (1, 'not-send', 'ul. Fiołkowa 24A 05-456 Warszawa', 'Bartosz Zdybel', 'zł', 'InPost', '/images/orders/python-tutorial.jpg', 'Book John Flanagan - “How to train your dog?”', 1200, '512014712');
INSERT INTO orders (id, type, address, bought_by, currency, delivery_company, img_url, item_full_name, price, telephone) VALUES (2, 'not-send', 'ul. Malowa 21A 05-456 Warszawa', 'Adrian Milewski', 'zł', 'DPD', '/images/orders/notebook.png', 'Book John Flanagan - “How to be your dog?”', 400, '512011212');
INSERT INTO orders (id, type, address, bought_by, currency, delivery_company, img_url, item_full_name, price, telephone) VALUES (3, 'not-send', 'ul. Malowa 21A 05-456 Warszawa', 'Adrian Milewski', 'zł', 'InPost', '/images/orders/harry-potter-books.webp', 'Book J.K Rowling - “How to be successful?”', 25, '687164589');
INSERT INTO orders (id, type, address, bought_by, currency, delivery_company, img_url, item_full_name, price, telephone) VALUES (4, 'not-send','ul. Malowa 21A 05-456 Warszawa', 'Adrian Milewski', 'zł', 'InPost', '/images/orders/java-tutorial.jpg', 'Book Rick Riordan - “Olimpijscy Herosi?”', 4852, '512011212');
INSERT INTO orders (id, type, address, bought_by, currency, delivery_company, img_url, item_full_name, price, telephone) VALUES (5, 'not-send','ul. Malowa 21A 05-456 Warszawa', 'Adrian Milewski', 'zł', 'DPD', '/images/orders/python-tutorial.jpg', 'Book John Flanagan - “How to be your dog?”', 41, '504530125');
INSERT INTO orders (id, type, address, bought_by, currency, delivery_company, img_url, item_full_name, price, telephone) VALUES (6, 'not-send', 'ul. Malowa 21A 05-456 Warszawa', 'Adrian Milewski', 'zł', 'InPost', '/images/orders/java-tutorial.jpg', 'Book Rick Riordan - “Olimpijscy Herosi?”', 120, '542789345');
INSERT INTO orders (id, type, address, bought_by, currency, delivery_company, img_url, item_full_name, price, telephone) VALUES (7, 'unpaid', 'ul. Malowa 21A 05-456 Warszawa', 'Adrian Milewski', 'zł', 'InPost', '/images/orders/python-tutorial.jpg', 'Book John Flanagan - “How to be your dog?”', 8880, '583431528');

INSERT INTO ranking_offer (id, full_item_name, img_url, number_of_sales, profit, currency, number_of_units_sold, number_of_unique_views) VALUES (1, 'Book J.K Rowling - “How to be successful?”', '/images/orders/notebook.png', 5, 1400, 'zł', 20, 4000 );
INSERT INTO ranking_offer (id, full_item_name, img_url, number_of_sales, profit, currency, number_of_units_sold, number_of_unique_views) VALUES (2, 'Book John Flanagan - “How to train your dog?”', '/images/orders/java-tutorial.jpg', 15, 100, 'zł', 100, 300 );
INSERT INTO ranking_offer (id, full_item_name, img_url, number_of_sales, profit, currency, number_of_units_sold, number_of_unique_views) VALUES (3, 'Book Rick Riordan - “Olimpijscy Herosi?”', '/images/orders/python-tutorial.jpg', 28, 7800, 'zł', 20, 700 );
INSERT INTO ranking_offer (id, full_item_name, img_url, number_of_sales, profit, currency, number_of_units_sold, number_of_unique_views) VALUES (4, 'Book John Flanagan - “How to train your dog?”', '/images/orders/harry-potter-books.webp', 20, 1400, 'zł', 20, 3480 );
INSERT INTO ranking_offer (id, full_item_name, img_url, number_of_sales, profit, currency, number_of_units_sold, number_of_unique_views) VALUES (5, 'Book Rick Riordan - “Olimpijscy Herosi?”', '/images/orders/python-tutorial.jpg', 10, 40, 'zł', 20, 8 );
INSERT INTO ranking_offer (id, full_item_name, img_url, number_of_sales, profit, currency, number_of_units_sold, number_of_unique_views) VALUES (6, 'Book J.K Rowling - “How to be successful?”', '/images/orders/java-tutorial.jpg', 20, 4500, 'zł', 20, 254 );